publish:
  address: 224.5.23.1:10003
server:
  auto-ref:
    address: :10007
  team:
    address: :10008
game:
  yellow-card-duration: 2m
  default-division: Div A
  normal:
    half-duration: 5m
    half-time-duration: 5m
    timeout-duration: 5m
    timeouts: 4
    break-after: 5m
  overtime:
    half-duration: 2m30s
    half-time-duration: 2m
    timeout-duration: 5m
    timeouts: 2
    break-after: 2m